### ISSUE TITLE
Could you release the code for CIFAR100 dataset?

### ISSUE THREAD

**Issue by cailincan0129** [xmed-lab/CLIPN#4]
Really appreciate your work. It is really impressive.
I'd like to replicate the results using CIFAR-100 as the in-distribution dataset. Is it possible to access the code for the CIFAR-100 dataset or receive guidance on image transformations and dataset splitting, such as using CIFAR-10 as the out-of-distribution dataset? 
Thank you very much.

**Comment by SiLangWHL** [comment]
Hi,

Thanks for your interest in our work. All experiments on Cifar are conducted based on CLIPN with hand-crafted prompts. 
The original plan is to release those codes this month. However, I found it hard to free up my time to reorganize them until mid-November due to several very important things, such as preparing for my PhD PQE. I will release them before the end of November. When the codes are released, I will contact you!

Bests,
Hualiang

**Comment by cailincan0129** [comment]
OK! Thank you very much!

**Comment by saya0312** [comment]
Sorry to bother you ...
I am interested in CLIPN and am eagerly awaiting the release of the code using CIFAR-10 and CIFAR-100.
When will it be released?

**Comment by SiLangWHL** [comment]
Hi, the code is coming. I am writing some necessary code comments. I will upload it tomorrow.

**Comment by SiLangWHL** [comment]
Hi, codes are released. Although there are still some hard codes that need to be optimized further, the main body of the code is ready to run.
